### ISSUE TITLE
feat: v2.0-1 checklist

### ISSUE THREAD

**Issue by kongwy** [kongwy/typecho-theme-minima#2]
## Typecho Manifest

- [x] style.css
- [x] screenshot.png
- [x] index.php
- [x] 404.php
- [x] archive.php
- [x] category.php `ignored: can be handled by archive.php`
- [x] search.php `ignored: can be handled by archive.php`
- [x] tag.php `ignored: can be handled by archive.php`
- [x] author.php `ignored: can be handled by archive.php`
- [x] comments.php
- [x] footer.php
- [x] functions.php
- [x] header.php
- [x] page.php
- [x] post.php
- [x] sidebar.php `ignored: Minima is a single-column theme`

## Upstream Clearance

- [x] _config.yml
- [x] index.ejs
- [x] archive.ejs
- [x] layout.ejs
- [x] page.ejs
- [x] post.ejs
- [x] tag.ejs `ignored: can be handled by archive.php in Typecho`
- [x] partial/comments.ejs
- [x] partial/footer.ejs
- [x] partial/google_analytics.ejs `comment: should let users customize through admin page instead`
- [x] partial/header.ejs
- [x] partial/pagination.ejs
- [x] partial/tcolor.ejs
